### ISSUE TITLE
species not in taxomy database are omitted [bug] 

### ISSUE THREAD

**Issue by jeffreyhanson** [bird-team/brisbane-birds-prototype#1]
Records for species that have species names not present in the BirdLife taxonomy table are omitted. Ideally, these species names should be resolved.

**Comment by dbl3raf** [comment]
eBird taxonomy is independent of BirdLife - it uses the [Clements checklist](http://www.birds.cornell.edu/clementschecklist/wp-content/uploads/2013/03/eBird_Taxonomy_v2016_9Aug2016.xlsx)

**Comment by jeffreyhanson** [comment]
Ok I'll update the taxonomy to use Clements.
