### ISSUE TITLE
Final grid size will probably be 1km2 or 2km2

### ISSUE THREAD

**Issue by dbl3raf** [bird-team/brisbane-birds-prototype#8]
Part of the idea of this book is to stimulate new fieldwork, making sure we've covered every inch of Brisbane with some minimum survey standard - 1km2 might not be achievable, but I'm certain 2km2 will be. Hopefully this isn't too much of an issue. If it is, I can get a decision made now about grid cell size.

**Comment by jeffreyhanson** [comment]
Grid size isn't a problem. The book has a [shapefile delineating the extent of the Brisbane LGA](https://github.com/bird-team/brisbane-birds/tree/master/data/study-area), and generates a grid automatically based on this grid and [the parameters in this file](https://github.com/bird-team/brisbane-birds/blob/master/code/parameters/data.toml).

So I just have to change that and it should update automatically.

**Comment by dbl3raf** [comment]
Awesome; it's un-be-lievable Jeff how much of this process is tweaks to live code.
